sudo: required
dist: trusty
language: cpp
compiler:
 - gcc

addons:
  apt:
     packages:
        - xserver-xorg-video-dummy
        - xpra
        - xorg-dev
        - libgl1-mesa-dev
        - libxrandr-dev
        - mesa-utils
        - libgl1-mesa-glx

before_install:
# Get Qt dev packages
 - export QT_VERSION=56
 - sudo add-apt-repository -y ppa:beineri/opt-qt561-trusty
 - sudo apt-get update -q
 - sudo apt-get -y install qt${QT_VERSION}declarative
 - sudo apt-get -y install qt${QT_VERSION}quickcontrols
 - sudo apt-get -y install qt${QT_VERSION}tools 
# Upgrade OpenGL drivers
 - sudo add-apt-repository ppa:oibaf/graphics-drivers
 - sudo apt-get update -qq -y
 - export DEBIAN_FRONTEND=noninteractive
 - sudo apt-get -yq --force-yes install libgl1-mesa-dev libgl1-mesa-glx mesa-common-dev libglapi-mesa libgbm1 libgl1-mesa-dri libxatracker-dev xvfb
 - glxinfo | grep version

before_script:
 - export DISPLAY=:99
 - export LIBGL_ALWYAS_SOFTWARE=1
 - xpra --xvfb="Xorg +extension GLX +extension RANDR +extension RENDER -config `pwd`/test/dummy.xorg.conf -logfile ${HOME}/.xpra/xorg.log"  start :99
 - sleep 3 
 - glxinfo
 - cat ${HOME}/.xpra/xorg.log

script:
 - source /opt/qt${QT_VERSION}/bin/qt${QT_VERSION}-env.sh
 - mkdir build
 - cd build
 - qmake ../qtopengl.pro QMAKE_CC=$CC QMAKE_CXX=$CXX
 - make
 - ./qtopengl

